### ISSUE TITLE
关于资源查询接口

### ISSUE THREAD

**Issue by damon008** [microsoft/frameworkcontroller#36]
请问关于namespace下的资源情况的查询有相关的接口文档吗？

**Comment by yqwang-ms** [comment]
**For resource allocation status, you can leverage:**
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#list-pod-v1-core
BTW, most schedulers also use it to calculate, such as https://github.com/microsoft/frameworkcontroller#recommended-kubernetes-scheduler

**For real resource utilization, you can leverage Prometheus as PAI did:**
https://github.com/microsoft/pai/tree/master/src/prometheus

**Comment by yqwang-ms** [comment]
@damon008  do you still have questions? If not, I will close the issue later :)

**Comment by yqwang-ms** [comment]
Close as no response
