### ISSUE TITLE
The required version of Golang is wrong

### ISSUE THREAD

**Issue by warmchang** [Microsoft/frameworkcontroller#4]
https://github.com/Microsoft/frameworkcontroller/blame/07c2a6c058b1c369cb9d3d339a042fc351e28d71/example/run/README.md#L100

![image](https://user-images.githubusercontent.com/13084624/50431450-ffa4fd00-0905-11e9-87d6-c3e8779ad9b2.png)

There is a typo in the description above, I think the golang version should be 1.10, and the description should be "Golang 1.10 or above and the ${GOPATH} is valid." :smiley:

**Comment by yqwang-ms** [comment]
Hi William, thank you to be the first one to report issue.
And it is indeed a typo.
I will fix it later. :)

**Comment by warmchang** [comment]
PTAL: https://github.com/Microsoft/frameworkcontroller/pull/5
